POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
  "id": "69a8b0f8-48fa-4aec-8d4a-e1537957226b",
  "first_name": "RIta",
  "last_name": "Oliver",
  "gender": "female",
  "roles": [
    "admin"
  ]
}

###
GET http://localhost:8000/api/v1/users
Accept: application/json

###


